import { Router } from 'express';
import { adminLogin, listUsers, manageUser, toggleVerify, resetUserPass, manageCoinsXP, manageReports, manageContent, setAnnouncement, getAnalytics } from '../controllers/admin.controller';
import { adminOnly } from '../middleware/auth';
const r = Router();
r.post('/login', adminLogin);
r.get('/users', adminOnly, listUsers);
r.post('/users/manage', adminOnly, manageUser);
r.post('/users/verify', adminOnly, toggleVerify);
r.post('/users/reset', adminOnly, resetUserPass);
r.post('/users/stats', adminOnly, manageCoinsXP);
r.get('/reports', adminOnly, manageReports);
r.post('/reports/handle', adminOnly, manageReports);
r.post('/content/delete', adminOnly, manageContent);
r.post('/announcement', adminOnly, setAnnouncement);
r.get('/analytics', adminOnly, getAnalytics);
export default r;
