import { Router } from 'express';
import { sendMessage, getConversation, markSeen } from '../controllers/dm.controller';
import { auth } from '../middleware/auth';
import { upload } from '../middleware/upload';
const r = Router();
r.use(auth);
r.post('/', upload.single('media'), sendMessage);
r.get('/:userId', getConversation);
r.post('/seen', markSeen);
export default r;
