import { Router } from 'express';
import { createReel, getReels, likeReel, commentReel } from '../controllers/reel.controller';
import { auth } from '../middleware/auth';
import { upload } from '../middleware/upload';
const r = Router();
r.use(auth);
r.post('/', upload.single('video'), createReel);
r.get('/feed', getReels);
r.post('/:id/like', likeReel);
r.post('/:id/comment', commentReel);
export default r;
